apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-agent-app
  template:
    metadata:
      labels:
        app: pr-agent-app
    spec:
      containers:
        - name: pr-agent-app
          image: ghcr.io/kaito-project/kaito-pr-agent:latest
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 3000
          # Use projected volume to combine secrets and config
          volumeMounts:
            - mountPath: "/app/pr_agent/settings_prod"
              name: combined-settings-volume
      volumes:
        - name: combined-settings-volume
          projected:
            sources:
            - secret:
                name: kaito-pr-agent-secrets
            - configMap:
                name: pr-agent-config
