apiVersion: v1
kind: Namespace
metadata:
  name: alb-infra
---
apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: pr-agent-alb
  namespace: alb-infra
spec:
  associations:
  - $ALB_SUBNET_ID