apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: pr-agent-gateway
  namespace: alb-infra
  annotations:
    alb.networking.azure.io/alb-namespace: alb-infra
    alb.networking.azure.io/alb-name: pr-agent-alb
spec:
  gatewayClassName: azure-alb-external  # this GatewayClass was created by ALB controller
  listeners:
    - name: http-listener
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All