name: PR-Agent E2E Tests

# =============================================================================
# DEVELOPMENT/TESTING WORKFLOW
# =============================================================================
# This workflow tests YOUR CODE CHANGES by building a Docker image from your
# modified code and running end-to-end tests against it.
# 
# Purpose: Validate that your code changes work correctly before merging
# Trigger: Pull requests to main, or manual triggers
# Code Used: YOUR MODIFIED CODE (builds fresh Docker image from your branch)
# 
# =============================================================================

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: '0 2 * * *' # Run nightly at 2 AM UTC

# Prevent multiple E2E tests from running simultaneously per PR/branch
concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    name: E2E Test PR-Agent Docker Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate unique image tag
        id: image_tag
        run: |
          # Create unique tag to avoid conflicts between parallel runs
          UNIQUE_TAG="kaito-project/kaito-pr-agent:test-${{ github.run_id }}-${{ github.run_attempt }}"
          echo "image_tag=${UNIQUE_TAG}" >> $GITHUB_OUTPUT
          echo "Using unique image tag: ${UNIQUE_TAG}"

      - name: Build PR-Agent Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: ${{ steps.image_tag.outputs.image_tag }}
          cache-from: type=gha,scope=dev-${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=dev-${{ github.ref_name }}
          target: test

      - name: Set up Python for E2E test
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install E2E test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest PyGithub python-dotenv
          # Install PR-Agent dependencies for the test environment
          pip install -r requirements.txt

      - name: Run E2E Test
        env:
          GITHUB.USER_TOKEN: ${{ secrets.E2E_GITHUB_TOKEN }}
          GITHUB.DEPLOYMENT_TYPE: user
          OPENAI_KEY: ${{ secrets.OPENAI_KEY || secrets.AZURE_OPENAI_API_KEY }}
          E2E_DOCKER_IMAGE: ${{ steps.image_tag.outputs.image_tag }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          if [ -z "${{ secrets.E2E_GITHUB_TOKEN }}" ]; then
            echo "❌ ERROR: E2E_GITHUB_TOKEN secret is not set"
            echo "Please create a Personal Access Token and add it as a repository secret"
            echo "Instructions: https://github.com/settings/tokens/new"
            exit 1
          fi
          
          echo "🧪 Running E2E test with built Docker image..."
          echo "Image: ${{ steps.image_tag.outputs.image_tag }}"
          echo "This test will:"
          echo "  1. Create a test PR in this repository"
          echo "  2. Run the built PR-Agent image on that PR"
          echo "  3. Validate that describe/review/improve tools work"
          echo "  4. Clean up the test PR"
          echo ""
          
          # Run the E2E test directly on the runner (not inside container)
          pytest -v tests/e2e_tests/test_pr_agent_e2e.py

      - name: Test Results Summary
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ E2E Test PASSED - Your PR-Agent changes work correctly!"
          else
            echo "❌ E2E Test FAILED - Check the logs above for details"
            exit 1
          fi
