# This workflow enables developers to call PR-Agents `/[actions]` in PR's comments and upon PR creation.
# Learn more at https://www.codium.ai/pr-agent/
# This is v0.2 of this workflow file

name: PR-Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # issue_comment:
  #   types: [created]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run Kaito PR Agent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Kaito PR Agent
        uses: ./.github/actions/kaito-pr-agent
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_key: ${{ secrets.OPENAI_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          anthropic_key: ${{ secrets.ANTHROPIC_API_KEY }}
          auto_describe: 'true'
          auto_review: 'true'
          auto_improve: 'true'
