name: PRAgent
on:
  pull_request:
    branches: ["*"]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on every pull request, respond to user comments
    steps:
    - name: Check Model Endpoint
      run: |
        curl -X GET "${{ secrets.KAITO_PR_REVIEWER_WORKSPACE_URL }}/models" -v
    
    - name: PR Agent action step
      id: pragent
      uses: Codium-ai/pr-agent@main
      env:
        CONFIG.MODEL: "hosted_vllm/qwen2.5-coder-7b-instruct"

        CONFIG.CUSTOM_MODEL_MAX_TOKENS: "32768"
        CONFIG.DUPLICATE_EXAMPLES: "true"

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB.USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        OLLAMA.API_BASE: ${{ secrets.KAITO_PR_REVIEWER_WORKSPACE_URL }}
        litellm.set_verbose: True

          # PR Agent configuration options
        #   pr_description.use_description_markers: "true"
        #   pr_description.include_generated_by_header: "true"
        #   github_action.auto_review: "true"
        #   github_action.auto_describe: "true"
        #   github_action.auto_improve: "true"
        #   pr_update_changelog.push_changelog_changes: "true"

# Run using docker
#      - name: Run PR Agent
#        id: pragent
#        run: |
#          docker run --rm -it \
#            -e CONFIG.MODEL="hosted_vllm/qwen2.5-coder-7b-instruct" \
#            -e CONFIG.FALLBACK_MODELS="hosted_vllm/qwen2.5-coder-7b-instruct" \
#            -e CONFIG.CUSTOM_MODEL_MAX_TOKENS="32768" \
#            -e CONFIG.DUPLICATE_EXAMPLES="true" \
#            -e GITHUB.USER_TOKEN="${{ secrets.API_TOKEN }}" \
#            -e GITHUB.DEPLOYMENT_TYPE="user" \
#            -e OLLAMA.API_BASE="http://host.docker.internal:5000/v1" \
#            codiumai/pr-agent:latest --pr_url ${{ github.event.pull_request.html_url
