
# =============================================================================
# PRODUCTION PR REVIEW WORKFLOW  
# =============================================================================
# This workflow uses the PRODUCTION version of PR-Agent to automatically
# review PRs opened against this repository using the Kaito backend.
#
# Purpose: Provide stable, reliable PR reviews for contributors
# Code Used: Production version (stable, tested)
# Backend: Kaito load balancer endpoint
# =============================================================================

name: PR-Agent Review (Production)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  issue_comment:
    types: [created]
  workflow_dispatch: # Manual trigger for testing

# Prevent conflicts between PR review and E2E tests
concurrency:
  group: pr-workflows-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel, let both run

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr_agent_job:
    # Skip E2E test PRs and bot PRs to avoid circular dependencies
    if: ${{ github.event.sender.type != 'Bot' && !contains(github.event.pull_request.title, '[E2E Test]') && !contains(github.event.pull_request.head.ref, 'e2e-test-') }}
    runs-on: ubuntu-latest
    name: Review PRs using Production PR-Agent
    steps:
    - name: Check Kaito Backend Health
      run: |
        echo "🔍 Checking Kaito backend health..."
        curl -X GET "${{ secrets.KAITO_PR_REVIEWER_WORKSPACE_URL }}/models" -v || echo "⚠️ Backend health check failed"
    
    - name: Run Production PR-Agent Review
      id: pragent
      uses: kaito-project/kaito-pr-agent@main  # Uses production version
      env:
        # Kaito backend configuration
        CONFIG.MODEL: "hosted_vllm/qwen2.5-coder-32b-instruct"
        CONFIG.CUSTOM_MODEL_MAX_TOKENS: "32768"
        CONFIG.DUPLICATE_PROMPT_EXAMPLES: "true"
        CONFIG.AI_TIMEOUT: "600"
        
        # GitHub configuration
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB.USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB.DEPLOYMENT_TYPE: "user"
        
        # Kaito endpoint
        OLLAMA.API_BASE: ${{ secrets.KAITO_PR_REVIEWER_WORKSPACE_URL }}
        
        # PR Agent features
        GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: "true"
        GITHUB_ACTION_CONFIG.AUTO_REVIEW: "true"
        GITHUB_ACTION_CONFIG.AUTO_IMPROVE: "true"

    - name: Review Summary
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ PR Review completed successfully!"
        else
          echo "❌ PR Review failed - check logs above"
        fi
