name: Unit Test

# =============================================================================
# UNIT TEST WORKFLOW
# =============================================================================
# This workflow validates code changes by building Docker images and running unit tests
# 
# Purpose: Quality gate for PRs and main branch
# Note: This does NOT publish images (see docker-release.yaml for that)
# =============================================================================

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # Skip E2E test PRs to avoid unnecessary resource usage
    if: ${{ !contains(github.event.pull_request.title, '[E2E Test]') && !contains(github.event.pull_request.head.ref, 'e2e-test-') }}
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: dockerx
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: build
        name: Build dev docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: kaito-project/kaito-pr-agent:test
          cache-from: type=gha,scope=dev-${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=dev-${{ github.ref_name }}
          target: test

      - id: test
        name: Test dev docker
        run: |
          docker run --rm kaito-project/kaito-pr-agent:test pytest -v tests/unittest
